Models/Booking.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Travelista.Models
{
    public class Booking
    {
        public int ID { get; set; }
        [ForeignKey("user")]
        public string User_ID { get; set; }
        public IdentityUser? user { get; set; }
        [ForeignKey("room")]
        public int? Room_id { get; set; }
        public Room? room { get; set; }
        [Display(Name ="Check In Date")]
        public DateTime Check_In_Date { get; set; }
        [Display(Name = "Check Out Date")]

        public DateTime Check_Out_Date { get; set; }
        [Display(Name = "Number of guests")]
        public int Num_Guests { get; set; }
        [Display(Name = "Room Type")]

        public string Room_type { get; set; }
        [Display(Name = "Total Price")]

        public decimal Total_Price { get; set; }
    }
}

Controllers/BookingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Travelista.Data;
using Travelista.Models;
using Travelista.repository.Interface;

namespace Travelista.Controllers
{
    public class BookingController : Controller

    {
       
        private readonly ApplicationDbContext dbContext;
        private readonly IBook _book;
        private readonly UserManager<IdentityUser> _userManager;
        public BookingController(ApplicationDbContext dbContext, IBook book, UserManager<IdentityUser> userManager)
        {
            this.dbContext = dbContext;
            _book = book;
            _userManager = userManager;
           
        }
        public async Task<IActionResult> Index(int id)
        {
            var errorMessage = TempData["message"] as string;
            if (!string.IsNullOrEmpty(errorMessage))
            {
                ViewBag.ErrorMessage = errorMessage;
            }
            var Room =  dbContext.Rooms.FirstOrDefault(r => r.ID == id);
            return View(Room);
        }
        [HttpPost]
        public async Task<IActionResult> Book(int room_id, int num_Guest, string roomType, DateTime strart_date, DateTime end_date)
        {
            string user_id = _userManager.GetUserId(User);
            Room room = new();
            room = dbContext.Rooms.FirstOrDefault(room => room.ID == room_id);
            Booking booking1 = new Booking();
            if (ModelState.IsValid)
            {
                if(strart_date.Date > end_date.Date)
				{
                    TempData["message"] = "Please enter the check in date less than the check out date";
                    return RedirectToAction("Index", new {id=room.ID});
				}
				else
				{
                    TimeSpan timeSpan = end_date - strart_date;
                    booking1.User_ID = user_id;
                    booking1.Room_id = room_id;
                    booking1.Num_Guests = num_Guest;
                    booking1.Room_type = roomType;
                    booking1.Check_In_Date = strart_date;
                    booking1.Check_Out_Date = end_date;
                    booking1.Total_Price = dbContext.Rooms.Find(room_id).Price_Per_Night * timeSpan.Days;
                   
                    return View("PaypalPayment",booking1);

                }
                 

            }
            return View();
             

        }
        [Route("Booking/Confirmation")]
        public async Task<IActionResult> Confirmation(string m)
        {
            Booking? booking = JsonConvert.DeserializeObject<Booking>(m);
           
            Booking book = new();
            book = _book.Book_Room(booking.User_ID,(int)booking.Room_id, booking.Num_Guests,
                booking.Room_type, booking.Check_In_Date, booking.Check_Out_Date, booking.Total_Price);
           

            return View("Confrmation");
        }



    }
}

Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Travelista.Data;
using Travelista.Models;
using Travelista.repository.Interface;

namespace Travelista.Controllers
{
    [Authorize(Roles = "admin")]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBook _book;
        public BookingsController(ApplicationDbContext context, IBook book)
        {
            _context = context;
            _book = book;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Bookings.Include(b => b.room).Include(b => b.user);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.room)
                .Include(b => b.user)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
       
        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.room)
                .Include(b => b.user)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           
            if (_context.Bookings == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Bookings'  is null.");
            }

            _book.Delete_Book(id);
            
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
          return (_context.Bookings?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Views/Booking/Confrmation.cshtml
<div class="container mt-5 text-center h3 alert alert-success" role="alert">
 Rooms booked successfully. Thank you for using our website
</div>

@section scripts{

<script>
let ob = window.localStorage.getItem("book");
ob = JSON.parse(ob);

$.ajax({
            type: 'POST',
            url: '/Booking/Confirmation',
            data: { user_id:, room_id, num_Guest, roomType, strart_date, end_date: },
            success: function() {
                // Handle success
            },
            error: function() {
                // Handle error
            }
        });
</script>
}

Views/Booking/Index.cshtml
@model Room


<div class="form-container mt-3" style="width:600px">
    <h1 class="title">Booking</h1>
        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
         {
       <p class="title alert alert-danger">@ViewBag.ErrorMessage</p>
        }
<form class="form" method="post" asp-action="Book" asp-controller="Booking" >
            <div class="input-group">
                <label>Room ID</label>
           <input type="number" name="id" value="@Model.ID" disabled />
           <input id="id" type="hidden" name="room_id" value="@Model.ID" />
            </div>
             <div class="input-group">
        <label>Guest</label>
        <input type="number" name="Guest" value="@Model.Occupancy" disabled/>
        <input id="guest" type="hidden" name="num_Guest" value="@Model.Occupancy" />
         </div>
         <div class="input-group">
        <label>roomType</label>
        <input type="text" name="room" value="@Model.Room_Type"disabled >
        <input id="type" type="hidden" name="roomType" value="@Model.Room_Type" />
         </div>
         <div class="input-group">
        <label>Check-in Date:</label>
        <input id="start" type="date" name="strart_date" required>
         </div>
         <div class="input-group">
        <label>Check-out Date:</label>
        <input id="end" type="date" name="end_date" required >
         </div>
         <div class="input-group">
        <button type="submit" id="paypal-btn" class="btn btn-primary mt-3 w-100">Book</button>
        </div>
              
</form>

</div>


              

               
    

Views/Booking/PaypalPayment.cshtml
@model Booking


  <div  class= "mt-5" style="margin-left:44%"  id="paypal-btn"></div>
 <span style="padding:5px"></span>

 
 @section scripts{
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
     var myModel = @Json.Serialize(Model);
     // console.log(myModel);
      localStorage.setItem("book", JSON.stringify(myModel));

</script>
<script>


let _total = @Html.Raw(Model.Total_Price);
   // TODO: fix this later
    paypal.Button.render({
        //Configure environment
        env: 'sandbox',
        client: {
            sandbox: 'AeReFctEqkO_dkiGN-bugPZtKefJRL9v62RRzXKK5UW0IWnlnO-bKDNLDBLrQeN2fk0GI4G0HWU83Ch0'
        },

        //Customize button
        locale: 'en_US',
        style: {
            size: 'small',
            color: 'gold',
            shape: 'pill'
        },
        commit: true,

        //Set up a payment
        payment: function (data, actions) {
            return actions.payment.create({
                transactions: [{
                    amount: {
                        total: _total,
                        currency: 'USD'
                    }
                }]
            });
        },
        
        //Execute the payment
        onAuthorize: function (data, actions) {
            return actions.payment.execute().then(function () {
                let ob = JSON.parse(window.localStorage.getItem("book"));
                var url = '@Url.Action("Confirmation", "Booking")' + '?m=' + encodeURIComponent(JSON.stringify(ob));
                window.location.href = url;
            });
          
        }

    }, '#paypal-btn')
</script>
}